USE workforce_db;


SELECT E.ID,E.FIRST_NAME,E.LAST_NAME,R.TITLE,D.NAME,R.SALARY,CONCAT(M.FIRST_NAME," ",M.LAST_NAME) AS "MANAGER" FROM
EMPLOYEE E 
LEFT JOIN ROLES R ON
E.role_id = R.ID 
LEFT JOIN DEPARTMENT D ON
R.department_id = D.ID 
LEFT JOIN EMPLOYEE M ON
E.manager_id = M.ID;

SELECT R.ID,R.TITLE,D.NAME AS "DEPARTMENT NAME",R.SALARY FROM
ROLES R,DEPARTMENT D WHERE R.department_id =D.ID;

SELECT DISTINCT M.ID, CONCAT(M.FIRST_NAME, " ", M.LAST_NAME) AS "MANAGER"
FROM EMPLOYEE E
JOIN EMPLOYEE M ON E.manager_id = M.ID
ORDER BY M.ID ASC;